@startuml
class AnnotationConfigApplicationContext{
   AnnotatedBeanDefinitionReader reader
   ClassPathBeanDefinitionScanner scanner
}
class GenericApplicationContext{
 DefaultListableBeanFactory beanFactory
 ApplicationContext parent
}
abstract AbstractApplicationContext{
  ResourcePatternResolver resourcePatternResolver
  ApplicationContext parent
}

class AnnotatedBeanDefinitionReader{
  BeanDefinitionRegistry registry
}

class ClassPathBeanDefinitionScanner{
     BeanDefinitionRegistry registry
}

class ClassPathScanningCandidateComponentProvider{
}
interface EnvironmentCapable
interface ResourceLoaderAware
interface Aware

interface BeanDefinitionRegistry
interface AliasRegistry

interface ResourcePatternResolver
interface ResourceLoader

AliasRegistry <|-- BeanDefinitionRegistry
BeanDefinitionRegistry <-- AnnotatedBeanDefinitionReader
AnnotatedBeanDefinitionReader <-- AnnotationConfigApplicationContext
ClassPathBeanDefinitionScanner <-- AnnotationConfigApplicationContext
BeanDefinitionRegistry <-- ClassPathBeanDefinitionScanner
ClassPathScanningCandidateComponentProvider <|-- ClassPathBeanDefinitionScanner
EnvironmentCapable <.. ClassPathScanningCandidateComponentProvider
ResourceLoaderAware <.. ClassPathScanningCandidateComponentProvider
Aware <.. ResourceLoaderAware
GenericApplicationContext <|-- AnnotationConfigApplicationContext
DefaultListableBeanFactory <-- GenericApplicationContext
ApplicationContext <-- GenericApplicationContext
AbstractApplicationContext <|-- GenericApplicationContext
ResourceLoader <.. ResourcePatternResolver
ResourcePatternResolver <-- AbstractApplicationContext
@enduml